# Generated by Django 4.1.5 on 2023-01-14 17:21

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('brief', models.TextField(blank=True, max_length=2500)),
                ('description', models.TextField(blank=True, max_length=2500)),
                ('price', models.IntegerField()),
                ('image_1', models.ImageField(upload_to=store.models.Product.upload_to_category_img)),
                ('image_2', models.ImageField(upload_to=store.models.Product.upload_to_category_img)),
                ('image_3', models.ImageField(upload_to=store.models.Product.upload_to_category_img)),
                ('feature_1_title', models.CharField(max_length=200)),
                ('features_image_1', models.ImageField(upload_to=store.models.Product.upload_to_category_features)),
                ('feature_2_title', models.CharField(max_length=200)),
                ('features_image_2', models.ImageField(upload_to=store.models.Product.upload_to_category_features)),
                ('feature_3_title', models.CharField(max_length=200)),
                ('features_image_3', models.ImageField(upload_to=store.models.Product.upload_to_category_features)),
                ('weight', models.IntegerField()),
                ('dimension_x', models.IntegerField()),
                ('dimension_y', models.IntegerField()),
                ('dimension_z', models.IntegerField()),
                ('warranty', models.IntegerField()),
                ('materials', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
        ),
    ]
