# Generated by Django 4.1.5 on 2023-01-09 05:07

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=30, unique=True)),
                ("description", models.TextField(blank=True, max_length=500)),
                ("price", models.IntegerField()),
                (
                    "image_1",
                    models.ImageField(
                        upload_to=store.models.Product.upload_to_category
                    ),
                ),
                (
                    "image_2",
                    models.ImageField(
                        blank=True, upload_to=store.models.Product.upload_to_category
                    ),
                ),
                (
                    "image_3",
                    models.ImageField(
                        blank=True, upload_to=store.models.Product.upload_to_category
                    ),
                ),
                ("stock", models.IntegerField()),
                ("is_available", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categories.category",
                    ),
                ),
            ],
        ),
    ]
