# Generated by Django 4.1.5 on 2023-01-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_rename_description_product_description_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description_1",
            field=models.TextField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_2",
            field=models.TextField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_3",
            field=models.TextField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_4",
            field=models.TextField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_5",
            field=models.TextField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_6",
            field=models.TextField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
